name: Deploy Node.js App to EC2 via Git Pull

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Checkout (optional for metadata, not used on EC2)
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/aws-nodejs-deploy
            git reset --hard   # Optional: discard local changes
            git pull
            npm install
            pm2 restart 0
